version: '3.9'

services:
  server:
    image: yandex/clickhouse-server:21.8.10.19
    # ports:
    #   - "8123:8123"
    #   - "9000:9000"
    # volumes:
    #   - ./data:/var/lib/clickhouse
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - ch_ntw

networks:
  ch_ntw:

